[cmake]
version = "3.15"
cmkr-include = "cmake/cmkr.cmake"

[project]
name = "x64dbg-automate"
include-before = [
	"cmake/msvc-static-runtime.cmake",
	"cmake/msvc-configurations.cmake",
]

[vcpkg]
version = "2025.01.13"
packages = ["cppzmq", "msgpack[boost]"]

[find-package.cppzmq]
required = true

[find-package.msgpack-cxx]
required = true

[find-package.Boost]
required = true

[fetch-content.x64dbg]
url = "https://sourceforge.net/projects/x64dbg/files/snapshots/snapshot_2025-08-19_19-40.zip"
sha1 = "59aceebe442319400e38fa651ceac8df507d9d93"
include-after = ["cmake/x64dbg.cmake"]

[template.plugin]
type = "shared"
add-function = "x64dbg_plugin"

[target.x64dbg-automate]
type = "plugin"
sources = [
    "src/*.cpp",
    "src/*.h",
]
link-libraries = ["cppzmq", "msgpack-cxx"]
compile-features = ["cxx_std_20"]